<?php

namespace App\Http\Controllers;

use App\Services\AI\ReportGenerator;
use Illuminate\Contracts\View\View;

class AIInsightsController extends Controller
{
    public function __construct(
        protected ReportGenerator $reportGenerator
    ) {}

    public function index(): View
{
    $report = $this->reportGenerator->getCurrentReport();

    if (!$report) {
        return view('ai-insights', [
            'alerts' => [],
            'executiveSummary' => [],
            'recommendations' => [],
            'risks' => [],
        ]);
    }

    $executiveSummary = [];

    if (!empty($report['executive_summary'])) {
        $executiveSummary[] = [
            'icon' => 'brain',
            'color' => 'blue',
            'text' => $report['executive_summary'],
            'sub_text' => 'Generated by Nexora AI',
        ];
    }

    $recommendations = collect($report['top_recommendations'] ?? [])
        ->map(function ($item) {
            return [
                'title' => $item['title'],
                'description' => $item['detail'],
                'impact' => 'High',
            ];
        })
        ->toArray();

    $risks = collect($report['risk_analysis'] ?? [])
        ->map(function ($item) {

            $color = match (strtolower($item['severity'])) {
                'critical' => 'red',
                'high' => 'red',
                'medium' => 'orange',
                'low' => 'green',
                default => 'blue',
            };

            return [
                'title' => $item['risk'],
                'description' => $item['detail'],
                'level' => ucfirst($item['severity']),
                'icon' => 'alert-triangle',
                'color' => $color,
            ];
        })
        ->toArray();

    return view('ai-insights', [
        'alerts' => [],
        'executiveSummary' => $executiveSummary,
        'recommendations' => $recommendations,
        'risks' => $risks,
    ]);
}
}